<?php

namespace Modules;

use Modules\Generals\Entities\Cities\City;
use Illuminate\Database\Seeder;

class city_venezuela extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();
        factory(City::class)->create(['province_id' => '1', 'city' => 'Maroa']);
        factory(City::class)->create(['province_id' => '1', 'city' => 'Puerto Ayacucho']);
        factory(City::class)->create(['province_id' => '1', 'city' => 'San Fernando de Atabapo']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Anaco']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Aragua de Barcelona']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Barcelona']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Boca de Uchire']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Cantaura']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Clarines']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'El Chaparro']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'El Pao Anzoátegui']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'El Tigre']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'El Tigrito']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Guanape']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Guanta']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Lechería']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Onoto']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Pariaguán']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Píritu']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Puerto La Cruz']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Puerto Píritu']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Sabana de Uchire']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'San Mateo Anzoátegui']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'San Pablo Anzoátegui']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'San Tomé']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Santa Ana de Anzoátegui']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Santa Fe Anzoátegui']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Santa Rosa']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Soledad']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Urica']);
        factory(City::class)->create(['province_id' => '2', 'city' => 'Valle de Guanape']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'Achaguas']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'Biruaca']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'Bruzual']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'El Amparo']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'El Nula']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'Elorza']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'Guasdualito']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'Mantecal']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'Puerto Páez']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'San Fernando de Apure']);
        factory(City::class)->create(['province_id' => '3', 'city' => 'San Juan de Payara']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Barbacoas']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Cagua']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Camatagua']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Choroní']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Colonia Tovar']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'El Consejo']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'La Victoria']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Las Tejerías']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Magdaleno']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Maracay']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Ocumare de La Costa']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Palo Negro']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'San Casimiro']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'San Mateo']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'San Sebastián']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Santa Cruz de Aragua']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Tocorón']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Turmero']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Villa de Cura']);
        factory(City::class)->create(['province_id' => '4', 'city' => 'Zuata']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Barinas']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Barinitas']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Barrancas']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Calderas']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Capitanejo']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Ciudad Bolivia']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'El Cantón']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Las Veguitas']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Libertad de Barinas']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Sabaneta']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Santa Bárbara de Barinas']);
        factory(City::class)->create(['province_id' => '5', 'city' => 'Socopó']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Caicara del Orinoco']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Canaima']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Ciudad Bolívar']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Ciudad Piar']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'El Callao']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'El Dorado']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'El Manteco']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'El Palmar']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'El Pao']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Guasipati']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Guri']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'La Paragua']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Matanzas']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Puerto Ordaz']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'San Félix']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Santa Elena de Uairén']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Tumeremo']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Unare']);
        factory(City::class)->create(['province_id' => '6', 'city' => 'Upata']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Bejuma']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Belén']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Campo de Carabobo']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Canoabo']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Central Tacarigua']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Chirgua']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Ciudad Alianza']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'El Palito']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Guacara']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Guigue']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Las Trincheras']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Los Guayos']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Mariara']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Miranda']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Montalbán']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Morón']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Naguanagua']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Puerto Cabello']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'San Joaquín']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Tocuyito']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Urama']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Valencia']);
        factory(City::class)->create(['province_id' => '7', 'city' => 'Vigirimita']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Aguirre']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Apartaderos Cojedes']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Arismendi']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Camuriquito']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'El Baúl']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'El Limón']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'El Pao Cojedes']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'El Socorro']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'La Aguadita']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Las Vegas']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Libertad de Cojedes']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Mapuey']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Piñedo']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Samancito']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'San Carlos']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Sucre']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Tinaco']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Tinaquillo']);
        factory(City::class)->create(['province_id' => '8', 'city' => 'Vallecito']);
        factory(City::class)->create(['province_id' => '9', 'city' => 'Tucupita']);
        factory(City::class)->create(['province_id' => '24', 'city' => 'Caracas']);
        factory(City::class)->create(['province_id' => '24', 'city' => 'El Junquito']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Adícora']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Boca de Aroa']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Cabure']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Capadare']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Capatárida']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Chichiriviche']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Churuguara']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Coro']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Cumarebo']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Dabajuro']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Judibana']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'La Cruz de Taratara']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'La Vela de Coro']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Los Taques']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Maparari']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Mene de Mauroa']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Mirimire']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Pedregal']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Píritu Falcón']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Pueblo Nuevo Falcón']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Puerto Cumarebo']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Punta Cardón']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Punto Fijo']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'San Juan de Los Cayos']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'San Luis']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Santa Ana Falcón']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Santa Cruz De Bucaral']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Tocopero']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Tocuyo de La Costa']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Tucacas']);
        factory(City::class)->create(['province_id' => '10', 'city' => 'Yaracal']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Altagracia de Orituco']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Cabruta']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Calabozo']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Camaguán']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Chaguaramas Guárico']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'El Socorro']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'El Sombrero']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Las Mercedes de Los Llanos']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Lezama']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Onoto']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Ortíz']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'San José de Guaribe']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'San Juan de Los Morros']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'San Rafael de Laya']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Santa María de Ipire']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Tucupido']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Valle de La Pascua']);
        factory(City::class)->create(['province_id' => '11', 'city' => 'Zaraza']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Aguada Grande']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Atarigua']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Barquisimeto']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Bobare']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Cabudare']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Carora']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Cubiro']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Cují']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Duaca']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'El Manzano']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'El Tocuyo']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Guaríco']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Humocaro Alto']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Humocaro Bajo']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'La Miel']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Moroturo']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Quíbor']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Río Claro']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Sanare']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Santa Inés']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Sarare']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Siquisique']);
        factory(City::class)->create(['province_id' => '12', 'city' => 'Tintorero']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Apartaderos Mérida']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Arapuey']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Bailadores']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Caja Seca']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Canaguá']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Chachopo']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Chiguara']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Ejido']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'El Vigía']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'La Azulita']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'La Playa']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Lagunillas Mérida']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Mérida']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Mesa de Bolívar']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Mucuchíes']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Mucujepe']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Mucuruba']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Nueva Bolivia']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Palmarito']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Pueblo Llano']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Santa Cruz de Mora']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Santa Elena de Arenales']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Santo Domingo']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Tabáy']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Timotes']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Torondoy']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Tovar']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Tucani']);
        factory(City::class)->create(['province_id' => '13', 'city' => 'Zea']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Araguita']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Carrizal']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Caucagua']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Chaguaramas Miranda']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Charallave']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Chirimena']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Chuspa']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Cúa']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Cupira']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Curiepe']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'El Guapo']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'El Jarillo']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Filas de Mariche']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Guarenas']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Guatire']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Higuerote']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Los Anaucos']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Los Teques']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Ocumare del Tuy']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Panaquire']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Paracotos']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Río Chico']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'San Antonio de Los Altos']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'San Diego de Los Altos']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'San Fernando del Guapo']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'San Francisco de Yare']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'San José de Los Altos']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'San José de Río Chico']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'San Pedro de Los Altos']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Santa Lucía']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Santa Teresa']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Tacarigua de La Laguna']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Tacarigua de Mamporal']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Tácata']);
        factory(City::class)->create(['province_id' => '14', 'city' => 'Turumo']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Aguasay']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Aragua de Maturín']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Barrancas del Orinoco']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Caicara de Maturín']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Caripe']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Caripito']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Chaguaramal']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Chaguaramas Monagas']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'El Furrial']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'El Tejero']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Jusepín']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'La Toscana']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Maturín']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Miraflores']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Punta de Mata']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Quiriquire']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'San Antonio de Maturín']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'San Vicente Monagas']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Santa Bárbara']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Temblador']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Teresen']);
        factory(City::class)->create(['province_id' => '15', 'city' => 'Uracoa']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Altagracia']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Boca de Pozo']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Boca de Río']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'El Espinal']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'El Valle del Espíritu Santo']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'El Yaque']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Juangriego']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'La Asunción']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'La Guardia']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Pampatar']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Porlamar']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Puerto Fermín']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Punta de Piedras']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'San Francisco de Macanao']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'San Juan Bautista']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'San Pedro de Coche']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Santa Ana de Nueva Esparta']);
        factory(City::class)->create(['province_id' => '16', 'city' => 'Villa Rosa']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Acarigua']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Agua Blanca']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Araure']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Biscucuy']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Boconoito']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Campo Elías']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Chabasquén']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Guanare']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Guanarito']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'La Aparición']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'La Misión']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Mesa de Cavacas']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Ospino']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Papelón']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Payara']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Pimpinela']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Píritu de Portuguesa']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'San Rafael de Onoto']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Santa Rosalía']);
        factory(City::class)->create(['province_id' => '17', 'city' => 'Turén']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Altos de Sucre']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Araya']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Cariaco']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Carúpano']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Casanay']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Cumaná']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Cumanacoa']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'El Morro Puerto Santo']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'El Pilar']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'El Poblado']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Guaca']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Guiria']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Irapa']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Manicuare']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Mariguitar']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Río Caribe']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'San Antonio del Golfo']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'San José de Aerocuar']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'San Vicente de Sucre']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Santa Fe de Sucre']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Tunapuy']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Yaguaraparo']);
        factory(City::class)->create(['province_id' => '18', 'city' => 'Yoco']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Abejales']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Borota']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Bramon']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Capacho']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Colón']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Coloncito']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Cordero']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'El Cobre']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'El Pinal']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Independencia']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'La Fría']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'La Grita']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'La Pedrera']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'La Tendida']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Las Delicias']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Las Hernández']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Lobatera']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Michelena']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Palmira']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Pregonero']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Queniquea']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Rubio']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'San Antonio del Tachira']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'San Cristobal']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'San José de Bolívar']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'San Josecito']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'San Pedro del Río']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Santa Ana Táchira']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Seboruco']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Táriba']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Umuquena']);
        factory(City::class)->create(['province_id' => '19', 'city' => 'Ureña']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Batatal']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Betijoque']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Boconó']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Carache']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Chejende']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Cuicas']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'El Dividive']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'El Jaguito']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Escuque']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Isnotú']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Jajó']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'La Ceiba']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'La Concepción de Trujllo']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'La Mesa de Esnujaque']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'La Puerta']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'La Quebrada']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Mendoza Fría']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Meseta de Chimpire']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Monay']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Motatán']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Pampán']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Pampanito']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Sabana de Mendoza']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'San Lázaro']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Santa Ana de Trujillo']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Tostós']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Trujillo']);
        factory(City::class)->create(['province_id' => '20', 'city' => 'Valera']);
        factory(City::class)->create(['province_id' => '21', 'city' => 'Carayaca']);
        factory(City::class)->create(['province_id' => '21', 'city' => 'Litoral']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Archipiélago Los Roques']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Aroa']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Boraure']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Campo Elías de Yaracuy']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Chivacoa']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Cocorote']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Farriar']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Guama']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Marín']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Nirgua']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Sabana de Parra']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Salom']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'San Felipe']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'San Pablo de Yaracuy']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Urachiche']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Yaritagua']);
        factory(City::class)->create(['province_id' => '22', 'city' => 'Yumare']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Bachaquero']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Bobures']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Cabimas']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Campo Concepción']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Campo Mara']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Campo Rojo']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Carrasquero']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Casigua']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Chiquinquirá']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Ciudad Ojeda']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'El Batey']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'El Carmelo']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'El Chivo']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'El Guayabo']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'El Mene']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'El Venado']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Encontrados']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Gibraltar']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Isla de Toas']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'La Concepción del Zulia']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'La Paz']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'La Sierrita']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Lagunillas del Zulia']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Las Piedras de Perijá']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Los Cortijos']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Machiques']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Maracaibo']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Mene Grande']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Palmarejo']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Paraguaipoa']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Potrerito']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Pueblo Nuevo del Zulia']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Puertos de Altagracia']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Punta Gorda']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Sabaneta de Palma']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'San Francisco']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'San José de Perijá']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'San Rafael del Moján']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'San Timoteo']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Santa Bárbara Del Zulia']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Santa Cruz de Mara']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Santa Cruz del Zulia']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Santa Rita']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Sinamaica']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Tamare']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Tía Juana']);
        factory(City::class)->create(['province_id' => '23', 'city' => 'Villa del Rosario']);
        factory(City::class)->create(['province_id' => '21', 'city' => 'La Guaira']);
        factory(City::class)->create(['province_id' => '21', 'city' => 'Catia La Mar']);
        factory(City::class)->create(['province_id' => '21', 'city' => 'Macuto']);
        factory(City::class)->create(['province_id' => '21', 'city' => 'Naiguatá']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Archipiélago Los Monjes']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Isla La Tortuga y Cayos adyacentes']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Isla La Sola']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Islas Los Testigos']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Islas Los Frailes']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Isla La Orchila']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Archipiélago Las Aves']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Isla de Aves']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Isla La Blanquilla']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Isla de Patos']);
        factory(City::class)->create(['province_id' => '25', 'city' => 'Islas Los Hermanos']);
    }
}
